export { default as LogoIcon } from './icons/Logo.svg';
export { default as SmallLogoIcon } from './icons/SmallLogo.svg';
export { default as SidebarMascotIcon1 } from './icons/SidebarMascot1.svg';
export { default as SidebarMascotIcon2 } from './icons/SidebarMascot2.svg';
export { default as SidebarMascotIcon3 } from './icons/SidebarMascot3.svg';
export { default as VillageIcon } from './icons/Village.svg';
export { default as LodingMascotIcon } from './icons/LodingMascot.svg';
export { default as LodingBackgroundIcon } from './icons/LodingBackground.svg';
export { default as CompleteCircleIcon } from './icons/CompleteCircle.svg';
